### ISSUE TITLE
Missin `torch` dependency in setup.py

### ISSUE THREAD

**Issue by ahmetkca** [lifeiteng/OmniSenseVoice#9]
I encountered an issue where the `omnisense transcribe` command fails due to a missing `torch` module. It seems that `torch` is not listed as a dependency in the `setup.py` file. Please add `torch` to the `install_requires` section to resolve this issue.
Was it intentional?

**Comment by lifeiteng** [comment]
thanks for reporting it, solved in https://github.com/lifeiteng/OmniSenseVoice/commit/76866254b84e4447fb7f5025e5f381b12d3b76f0
